### ISSUE TITLE
Numpy requirement in setup is causing installation problems

### ISSUE THREAD

**Issue by ATajadod94** [the-virtual-brain/tvb-gdist#19]
Tried moving a notebook to binder and I wasn't able to do it because of the numpy requirement. Also had trouble with my local venv setup, but that was easy to solve

**Comment by ayan-b** [comment]
Seems like this issue is resolved in #28. As a side note perhaps we should pin the versions in `requirements.txt`.

**Comment by ayan-b** [comment]
It appears I was wrong about numpy installation issue. While running `python setup.py build_ext --inplace` there are a bunch of warnings before #28 (https://pastebin.com/nzwR8Czv) and after #28 (https://pastebin.com/jhSN8c2R) with the warning of only auto_ptr being removed. Note that it doesn't fail to build the extension.

However, there is no issue with `python setup.py install`. It may be noted that they are not particularly numpy errors.

**Comment by alexpron** [comment]
Dear all,

 I tried to install tvb-gdist from pypi using pip install command under linux distribution (xenial) and I encounter the numpy not found problem that causes the installation to crash. I also tried to install it from latest source (github) thinking the problem was solved but the installation still crashes (see travis log file enclosed). Using windows i do not encounter any problem since there are available binaries in Pypi. Any idea how I could solve this issue ? 

<img width="687" alt="install_tvb_gdist_xenial" src="https://user-images.githubusercontent.com/45215023/84034338-7b7bf380-a99a-11ea-80de-6432ce97e574.PNG">

**Comment by ayan-b** [comment]
Can you please try `pip install numpy` before installing tvb-gdist?

**Comment by alexpron** [comment]
Hello anyan-b,
 thank you for your quick answer. If I explicitely install numpy and cython beforetvb-gdist everything works fine (see below). The thing is numpy and cython need to be installed before whereas scipy is gathered automatically. Hence, if I set tvb-gdist as a dependency of my project through the setup.py mechanism, the install crashes. A quick solution would be  the user need to explicitely install numpy and cython first. But, if possible I would like to automatically trigger the install of tvb-gdist and its depencies using the pip install . or setup.py install mechanism. Any idea why the second way is crashing ?
Thank you for your time

<img width="687" alt="install_tvb_gdist_xenial_dependencies" src="https://user-images.githubusercontent.com/45215023/84041424-1d540e00-a9a4-11ea-8e41-d29678565457.PNG">

**Comment by ayan-b** [comment]
Hi @alexpron,

Made #39 for that. Please use the repo for now `pip install git+https://github.com/the-virtual-brain/tvb-gdist`.

**Comment by alexpron** [comment]
Thank you very much Ayan Banerjee for taking the time to solve this isue. I
wish you all the best
Yours faithfully
Alexandre Pron

Le lun. 8 juin 2020 à 16:32, Ayan Banerjee <notifications@github.com> a
écrit :

**Comment by liadomide** [comment]
I just tested in a clean/empty env and I confirm that this is still happening for tvb-gdist version 2.0.1 (latest on Pypi) in any env where a whl does not exist and the tar.gz sources are used.

**Comment by liadomide** [comment]
But as I just merged #38 from @ayan-b it works to temporarily use
`pip install git+https://github.com/the-virtual-brain/tvb-gdist`
In the next few days we will try to make a new release on Pypi, to officially fix there too. Thanks @alexpron for reporting and documenting this

**Comment by alexpron** [comment]
I guess this is due to the import numpy statement inside the setup.py file,
pyproject.toml file may be the most promising lead but for un know reason
it does not work

**Comment by alexpron** [comment]
Just retested now. Works perfectly fine in Ubuntu and MacOsX raw environnement. Thank you @ayan-b and @liadomide
